
default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:993403381433:android:e69f526f770dd1152f9d68",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "MohamedElbakrawy70@gmail.com",
    release_notes: "New release with fastlane Available"
  )
  end
end